{
 "title": "Cosmos",
 "description": "Dashboard based on zhangyelong/cosmos-dashboard",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(tendermint_consensus_height, chain_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tendermint_consensus_height{chain_id=\"$chain_id\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$chain_id overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "<img width=\"160px\" src=\"https://raw.githubusercontent.com/zhangyelong/cosmos-dashboard/master/logo/$chain_id.png\" />"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Block Height",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tendermint_consensus_height{chain_id=\"$chain_id\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total Transactions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tendermint_consensus_total_txs{chain_id=\"$chain_id\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Avg Block Time",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "tendermint_consensus_block_interval_seconds{chain_id=\"$chain_id\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Bonded Tokens",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Validators",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "tendermint_consensus_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "tendermint_consensus_missing_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "Missing"
      },
      {
       "expr": "tendermint_consensus_byzantine_validators{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "Byzantine"
      }
     ]
    },
    {
     "title": "Voting Power",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tendermint_consensus_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "Online"
      },
      {
       "expr": "tendermint_consensus_missing_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "Missing"
      },
      {
       "expr": "tendermint_consensus_byzantine_validators_power{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "Byzantine"
      }
     ]
    },
    {
     "title": "Block Size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tendermint_consensus_block_size_bytes{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "Block Size"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tendermint_consensus_num_txs{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "Transactions"
      }
     ]
    }
   ]
  },
  {
   "title": "instance overview: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connected Peers",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "tendermint_p2p_peers{chain_id=\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Unconfirmed Transactions",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "tendermint_mempool_size{chain_id=\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Failed Transactions",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tendermint_mempool_failed_txs{chain_id=\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Recheck Times",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tendermint_mempool_recheck_times{chain_id=\"$chain_id\", instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "Total Network Input",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tendermint_p2p_peer_receive_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    },
    {
     "title": "Total Network Output",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "tendermint_p2p_peer_send_bytes_total{chain_id=\"$chain_id\", instance=\"$instance\"}",
       "legendFormat": "{{peer_id}}"
      }
     ]
    }
   ]
  }
 ]
}