{
 "title": "Laconic",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Peers Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "tendermint_p2p_peers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "tendermint_consensus_latest_block_height",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}