global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: laconic # example, how to connect prometheus to Laconic
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - laconic:26660 # `laconic` host if is running via docker compose.
          # - host.docker.internal:26660 # host machine on "docker for mac"
          # - 192.168.3.19:26660
